---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: borrowlist3000
spec:
    selector:
        matchLabels:
            app.kubernetes.io/component: web
            app.kubernetes.io/name: borrowlist3000_server
    template:
        metadata:
            labels:
                app.kubernetes.io/component: web
                app.kubernetes.io/name: borrowlist3000_server
        spec:
            containers:
                -   name: server
                    image: ghcr.io/ftsell/borrowlist3000
                    envFrom:
                        -   configMapRef:
                                name: borrowlist3000
                    ports:
                        -   name: http
                            containerPort: 8000
                    readinessProbe:
                        httpGet:
                            port: http
                    livenessProbe:
                        httpGet:
                            port: http

