---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: borrowlist3000
commonLabels:
    app.kubernetes.io/part-of: borrowlist3000
commonAnnotations:
    app.kubernetes.io/repository: "https://github.com/ftsell/borrowList3000/"

resources:
    - .k8s/namespace.yml
    - .k8s/deployment.yml
    - .k8s/service.yml

configMapGenerator:
    -   name: borrowlist3000
        envs:
            - .k8s/config.env
