management:
  endpoint:
    health:
      probes:
        enabled: true

server:
  servlet:
    session:
      timeout: 365d

springdoc:
  paths-to-match: /api/**
  api-docs:
    path: /api/schema
  swagger-ui:
    path: /api/swagger-ui