/* tslint:disable */
/* eslint-disable */
/**
 * Thing-People-List Api
 * Public API of the Thing-People-List Service. Thing-People-List is a Web-Service to keep track of which people did what i.e. who borrowed what from you.
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: dev@finn-thorben.me
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
/**
 *
 * @export
 * @interface PatchThingListRequest
 */
export interface PatchThingListRequest {
  /**
   *
   * @type {string}
   * @memberof PatchThingListRequest
   */
  name?: string;
}

export function PatchThingListRequestFromJSON(
  json: any
): PatchThingListRequest {
  return PatchThingListRequestFromJSONTyped(json, false);
}

export function PatchThingListRequestFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): PatchThingListRequest {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    name: !exists(json, "name") ? undefined : json["name"],
  };
}

export function PatchThingListRequestToJSON(
  value?: PatchThingListRequest | null
): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    name: value.name,
  };
}
