/* tslint:disable */
/* eslint-disable */
/**
 * Thing-People-List Api
 * Public API of the Thing-People-List Service. Thing-People-List is a Web-Service to keep track of which people did what i.e. who borrowed what from you.
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: dev@finn-thorben.me
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
/**
 *
 * @export
 * @interface Problem
 */
export interface Problem {
  /**
   *
   * @type {string}
   * @memberof Problem
   */
  type?: string;
  /**
   *
   * @type {string}
   * @memberof Problem
   */
  title?: string;
  /**
   *
   * @type {number}
   * @memberof Problem
   */
  status?: number;
  /**
   *
   * @type {string}
   * @memberof Problem
   */
  detail?: string;
  /**
   *
   * @type {string}
   * @memberof Problem
   */
  instance?: string;
}

export function ProblemFromJSON(json: any): Problem {
  return ProblemFromJSONTyped(json, false);
}

export function ProblemFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): Problem {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    type: !exists(json, "type") ? undefined : json["type"],
    title: !exists(json, "title") ? undefined : json["title"],
    status: !exists(json, "status") ? undefined : json["status"],
    detail: !exists(json, "detail") ? undefined : json["detail"],
    instance: !exists(json, "instance") ? undefined : json["instance"],
  };
}

export function ProblemToJSON(value?: Problem | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    type: value.type,
    title: value.title,
    status: value.status,
    detail: value.detail,
    instance: value.instance,
  };
}
