/* tslint:disable */
/* eslint-disable */
/**
 * Thing-People-List Api
 * Public API of the Thing-People-List Service. Thing-People-List is a Web-Service to keep track of which people did what i.e. who borrowed what from you.
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: dev@finn-thorben.me
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
/**
 *
 * @export
 * @interface SessionWithTokenDto
 */
export interface SessionWithTokenDto {
  /**
   *
   * @type {string}
   * @memberof SessionWithTokenDto
   */
  sessionId: string;
  /**
   *
   * @type {string}
   * @memberof SessionWithTokenDto
   */
  ipAddress: string;
  /**
   *
   * @type {string}
   * @memberof SessionWithTokenDto
   */
  userAgent: string;
  /**
   *
   * @type {Date}
   * @memberof SessionWithTokenDto
   */
  creationTime: Date;
  /**
   *
   * @type {Date}
   * @memberof SessionWithTokenDto
   */
  lastAccessTime: Date;
  /**
   *
   * @type {string}
   * @memberof SessionWithTokenDto
   */
  token: string;
  /**
   *
   * @type {boolean}
   * @memberof SessionWithTokenDto
   */
  current?: boolean;
}

export function SessionWithTokenDtoFromJSON(json: any): SessionWithTokenDto {
  return SessionWithTokenDtoFromJSONTyped(json, false);
}

export function SessionWithTokenDtoFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): SessionWithTokenDto {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    sessionId: json["sessionId"],
    ipAddress: json["ipAddress"],
    userAgent: json["userAgent"],
    creationTime: new Date(json["creationTime"]),
    lastAccessTime: new Date(json["lastAccessTime"]),
    token: json["token"],
    current: !exists(json, "current") ? undefined : json["current"],
  };
}

export function SessionWithTokenDtoToJSON(
  value?: SessionWithTokenDto | null
): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    sessionId: value.sessionId,
    ipAddress: value.ipAddress,
    userAgent: value.userAgent,
    creationTime: value.creationTime.toISOString(),
    lastAccessTime: value.lastAccessTime.toISOString(),
    token: value.token,
    current: value.current,
  };
}
