# Generated by Django 3.2.6 on 2021-08-29 11:41

import borrowlist3000_db.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.UUIDField(default=borrowlist3000_db.models.uuid_default, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=60, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BorrowerModel',
            fields=[
                ('id', models.UUIDField(default=borrowlist3000_db.models.uuid_default, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('lender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='borrowers', related_query_name='borrower', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BorrowedItemModel',
            fields=[
                ('id', models.UUIDField(default=borrowlist3000_db.models.uuid_default, primary_key=True, serialize=False)),
                ('specifier', models.CharField(max_length=120)),
                ('description', models.CharField(blank=True, max_length=240)),
                ('date_borrowed', models.DateField(auto_now_add=True)),
                ('borrower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='borrowed_items', related_query_name='borrowed_item', to='borrowlist3000_db.borrowermodel')),
            ],
        ),
        migrations.AddConstraint(
            model_name='borrowermodel',
            constraint=models.UniqueConstraint(fields=('lender', 'name'), name='unique_borrowers_per_user'),
        ),
    ]
