# Generated by Django 3.2.6 on 2021-09-12 10:49

import borrowlist3000_db.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('borrowlist3000_db', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PasswordReset',
            fields=[
                ('token', models.CharField(default=borrowlist3000_db.models.password_reset_token_default, max_length=60, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='password_resets', related_query_name='password_reset', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
