/* tslint:disable */
/* eslint-disable */
/**
 * Thing-People-List Api
 * Public API of the Thing-People-List Service. Thing-People-List is a Web-Service to keep track of which people did what i.e. who borrowed what from you.
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: dev@finn-thorben.me
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from "../runtime";
import type {
  CreateThingListRequest,
  PatchThingListRequest,
  Problem,
  ThingListDto,
} from "../models";

import {
  CreateThingListRequestFromJSON,
  CreateThingListRequestToJSON,
  PatchThingListRequestFromJSON,
  PatchThingListRequestToJSON,
  ProblemFromJSON,
  ProblemToJSON,
  ThingListDtoFromJSON,
  ThingListDtoToJSON,
} from "../models";

export interface DeleteRequest {
  id: string;
}

export interface Create2Request {
  createThingListRequest: CreateThingListRequest;
}

export interface GetByIdRequest {
  id: string;
}

export interface UpdateByIdRequest {
  id: string;
  patchThingListRequest: PatchThingListRequest;
}

/**
 *
 */
export class ThingListControllerApi extends runtime.BaseAPI {
  /**
   * Delete the specified list
   */
  async _deleteRaw(
    requestParameters: DeleteRequest,
    initOverrides?: RequestInit
  ): Promise<runtime.ApiResponse<void>> {
    if (requestParameters.id === null || requestParameters.id === undefined) {
      throw new runtime.RequiredError(
        "id",
        "Required parameter requestParameters.id was null or undefined when calling _delete."
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    if (this.configuration && this.configuration.apiKey) {
      headerParameters["Authorization"] =
        this.configuration.apiKey("Authorization"); // token authentication
    }

    const response = await this.request(
      {
        path: `/api/lists/{id}`.replace(
          `{${"id"}}`,
          encodeURIComponent(String(requestParameters.id))
        ),
        method: "DELETE",
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides
    );

    return new runtime.VoidApiResponse(response);
  }

  /**
   * Delete the specified list
   */
  async _delete(
    requestParameters: DeleteRequest,
    initOverrides?: RequestInit
  ): Promise<void> {
    await this._deleteRaw(requestParameters, initOverrides);
  }

  /**
   * Create a new list
   */
  async create2Raw(
    requestParameters: Create2Request,
    initOverrides?: RequestInit
  ): Promise<runtime.ApiResponse<ThingListDto>> {
    if (
      requestParameters.createThingListRequest === null ||
      requestParameters.createThingListRequest === undefined
    ) {
      throw new runtime.RequiredError(
        "createThingListRequest",
        "Required parameter requestParameters.createThingListRequest was null or undefined when calling create2."
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters["Content-Type"] = "application/json";

    if (this.configuration && this.configuration.apiKey) {
      headerParameters["Authorization"] =
        this.configuration.apiKey("Authorization"); // token authentication
    }

    const response = await this.request(
      {
        path: `/api/lists/`,
        method: "POST",
        headers: headerParameters,
        query: queryParameters,
        body: CreateThingListRequestToJSON(
          requestParameters.createThingListRequest
        ),
      },
      initOverrides
    );

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      ThingListDtoFromJSON(jsonValue)
    );
  }

  /**
   * Create a new list
   */
  async create2(
    requestParameters: Create2Request,
    initOverrides?: RequestInit
  ): Promise<ThingListDto> {
    const response = await this.create2Raw(requestParameters, initOverrides);
    return await response.value();
  }

  /**
   * List all lists
   */
  async getAll1Raw(
    initOverrides?: RequestInit
  ): Promise<runtime.ApiResponse<Array<ThingListDto>>> {
    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    if (this.configuration && this.configuration.apiKey) {
      headerParameters["Authorization"] =
        this.configuration.apiKey("Authorization"); // token authentication
    }

    const response = await this.request(
      {
        path: `/api/lists/`,
        method: "GET",
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides
    );

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      jsonValue.map(ThingListDtoFromJSON)
    );
  }

  /**
   * List all lists
   */
  async getAll1(initOverrides?: RequestInit): Promise<Array<ThingListDto>> {
    const response = await this.getAll1Raw(initOverrides);
    return await response.value();
  }

  /**
   * Retrieve information about a specific list
   */
  async getByIdRaw(
    requestParameters: GetByIdRequest,
    initOverrides?: RequestInit
  ): Promise<runtime.ApiResponse<ThingListDto>> {
    if (requestParameters.id === null || requestParameters.id === undefined) {
      throw new runtime.RequiredError(
        "id",
        "Required parameter requestParameters.id was null or undefined when calling getById."
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    if (this.configuration && this.configuration.apiKey) {
      headerParameters["Authorization"] =
        this.configuration.apiKey("Authorization"); // token authentication
    }

    const response = await this.request(
      {
        path: `/api/lists/{id}`.replace(
          `{${"id"}}`,
          encodeURIComponent(String(requestParameters.id))
        ),
        method: "GET",
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides
    );

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      ThingListDtoFromJSON(jsonValue)
    );
  }

  /**
   * Retrieve information about a specific list
   */
  async getById(
    requestParameters: GetByIdRequest,
    initOverrides?: RequestInit
  ): Promise<ThingListDto> {
    const response = await this.getByIdRaw(requestParameters, initOverrides);
    return await response.value();
  }

  /**
   * Update the specified list with the given data
   */
  async updateByIdRaw(
    requestParameters: UpdateByIdRequest,
    initOverrides?: RequestInit
  ): Promise<runtime.ApiResponse<ThingListDto>> {
    if (requestParameters.id === null || requestParameters.id === undefined) {
      throw new runtime.RequiredError(
        "id",
        "Required parameter requestParameters.id was null or undefined when calling updateById."
      );
    }

    if (
      requestParameters.patchThingListRequest === null ||
      requestParameters.patchThingListRequest === undefined
    ) {
      throw new runtime.RequiredError(
        "patchThingListRequest",
        "Required parameter requestParameters.patchThingListRequest was null or undefined when calling updateById."
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters["Content-Type"] = "application/json";

    if (this.configuration && this.configuration.apiKey) {
      headerParameters["Authorization"] =
        this.configuration.apiKey("Authorization"); // token authentication
    }

    const response = await this.request(
      {
        path: `/api/lists/{id}`.replace(
          `{${"id"}}`,
          encodeURIComponent(String(requestParameters.id))
        ),
        method: "PATCH",
        headers: headerParameters,
        query: queryParameters,
        body: PatchThingListRequestToJSON(
          requestParameters.patchThingListRequest
        ),
      },
      initOverrides
    );

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      ThingListDtoFromJSON(jsonValue)
    );
  }

  /**
   * Update the specified list with the given data
   */
  async updateById(
    requestParameters: UpdateByIdRequest,
    initOverrides?: RequestInit
  ): Promise<ThingListDto> {
    const response = await this.updateByIdRaw(requestParameters, initOverrides);
    return await response.value();
  }
}
