/* tslint:disable */
/* eslint-disable */
/**
 * Thing-People-List Api
 * Public API of the Thing-People-List Service. Thing-People-List is a Web-Service to keep track of which people did what i.e. who borrowed what from you.
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: dev@finn-thorben.me
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
/**
 *
 * @export
 * @interface ChangeUserDto
 */
export interface ChangeUserDto {
  /**
   *
   * @type {string}
   * @memberof ChangeUserDto
   */
  password: string;
}

export function ChangeUserDtoFromJSON(json: any): ChangeUserDto {
  return ChangeUserDtoFromJSONTyped(json, false);
}

export function ChangeUserDtoFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): ChangeUserDto {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    password: json["password"],
  };
}

export function ChangeUserDtoToJSON(value?: ChangeUserDto | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    password: value.password,
  };
}
