/* tslint:disable */
/* eslint-disable */
/**
 * Thing-People-List Api
 * Public API of the Thing-People-List Service. Thing-People-List is a Web-Service to keep track of which people did what i.e. who borrowed what from you.
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: dev@finn-thorben.me
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
/**
 *
 * @export
 * @interface CreateThingListRequest
 */
export interface CreateThingListRequest {
  /**
   *
   * @type {string}
   * @memberof CreateThingListRequest
   */
  name: string;
}

export function CreateThingListRequestFromJSON(
  json: any
): CreateThingListRequest {
  return CreateThingListRequestFromJSONTyped(json, false);
}

export function CreateThingListRequestFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): CreateThingListRequest {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    name: json["name"],
  };
}

export function CreateThingListRequestToJSON(
  value?: CreateThingListRequest | null
): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    name: value.name,
  };
}
