/* tslint:disable */
/* eslint-disable */
/**
 * Thing-People-List Api
 * Public API of the Thing-People-List Service. Thing-People-List is a Web-Service to keep track of which people did what i.e. who borrowed what from you.
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: dev@finn-thorben.me
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
/**
 *
 * @export
 * @interface PendingSessionDto
 */
export interface PendingSessionDto {
  /**
   *
   * @type {string}
   * @memberof PendingSessionDto
   */
  token: string;
  /**
   *
   * @type {Date}
   * @memberof PendingSessionDto
   */
  expirationDate: Date;
}

export function PendingSessionDtoFromJSON(json: any): PendingSessionDto {
  return PendingSessionDtoFromJSONTyped(json, false);
}

export function PendingSessionDtoFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): PendingSessionDto {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    token: json["token"],
    expirationDate: new Date(json["expirationDate"]),
  };
}

export function PendingSessionDtoToJSON(value?: PendingSessionDto | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    token: value.token,
    expirationDate: value.expirationDate.toISOString(),
  };
}
