/* tslint:disable */
/* eslint-disable */
/**
 * Thing-People-List Api
 * Public API of the Thing-People-List Service. Thing-People-List is a Web-Service to keep track of which people did what i.e. who borrowed what from you.
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: dev@finn-thorben.me
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
/**
 *
 * @export
 * @interface ThingListDto
 */
export interface ThingListDto {
  /**
   *
   * @type {string}
   * @memberof ThingListDto
   */
  id: string;
  /**
   *
   * @type {string}
   * @memberof ThingListDto
   */
  name: string;
}

export function ThingListDtoFromJSON(json: any): ThingListDto {
  return ThingListDtoFromJSONTyped(json, false);
}

export function ThingListDtoFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): ThingListDto {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    id: json["id"],
    name: json["name"],
  };
}

export function ThingListDtoToJSON(value?: ThingListDto | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    id: value.id,
    name: value.name,
  };
}
