/* tslint:disable */
/* eslint-disable */
/**
 * Thing-People-List Api
 * Public API of the Thing-People-List Service. Thing-People-List is a Web-Service to keep track of which people did what i.e. who borrowed what from you.
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: dev@finn-thorben.me
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
/**
 *
 * @export
 * @interface ThingDto
 */
export interface ThingDto {
  /**
   *
   * @type {string}
   * @memberof ThingDto
   */
  id: string;
  /**
   *
   * @type {string}
   * @memberof ThingDto
   */
  name: string;
  /**
   *
   * @type {string}
   * @memberof ThingDto
   */
  description?: string;
  /**
   *
   * @type {string}
   * @memberof ThingDto
   */
  listName: string;
  /**
   *
   * @type {string}
   * @memberof ThingDto
   */
  personName: string;
}

export function ThingDtoFromJSON(json: any): ThingDto {
  return ThingDtoFromJSONTyped(json, false);
}

export function ThingDtoFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): ThingDto {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    id: json["id"],
    name: json["name"],
    description: !exists(json, "description") ? undefined : json["description"],
    listName: json["listName"],
    personName: json["personName"],
  };
}

export function ThingDtoToJSON(value?: ThingDto | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    id: value.id,
    name: value.name,
    description: value.description,
    listName: value.listName,
    personName: value.personName,
  };
}
